export const TOPICS = [
  { id: "global-finance", label: "Globalización y finanzas internacionales", group: "Globalización" },
  { id: "origins", label: "Orígenes de las finanzas internacionales", group: "Globalización" },
  { id: "interdependence", label: "Interdependencia mundial", group: "Globalización" },
  { id: "globalization-concept", label: "Concepto de globalización", group: "Globalización" },
  { id: "globalization-risks", label: "Críticas, riesgos y desafíos de la globalización", group: "Globalización" },
  { id: "ims", label: "Sistema Monetario Internacional", group: "Sistema monetario" },
  { id: "monetary-systems", label: "Principales sistemas monetarios mundiales", group: "Sistema monetario" },
  { id: "ims-history", label: "Historia del sistema monetario internacional", group: "Sistema monetario" },
  { id: "bop-crisis", label: "Crisis de balanza de pagos", group: "Balanza de pagos" },
  { id: "bop", label: "Balanza de pagos", group: "Balanza de pagos" },
  { id: "bop-components", label: "Componentes de la balanza de pagos", group: "Balanza de pagos" },
  { id: "transactions", label: "Transacciones registradas", group: "Balanza de pagos" },
  { id: "bop-interpretation", label: "Interpretación de la balanza de pagos", group: "Balanza de pagos" },
  { id: "double-entry", label: "Contabilidad doble", group: "Balanza de pagos" },
  { id: "mexico-current-account", label: "Cuenta corriente y déficit en México", group: "Balanza de pagos" },
  { id: "fx-theory", label: "Teoría del tipo de cambio", group: "Tipo de cambio" },
  { id: "fx-market", label: "Definición y funciones del mercado de divisas", group: "Tipo de cambio" },
  { id: "cross-rate", label: "Tipo de cambio cruzado", group: "Tipo de cambio" },
  { id: "effective-rate", label: "Tipo de cambio efectivo", group: "Tipo de cambio" },
  { id: "ppp", label: "Paridad del poder adquisitivo", group: "Tipo de cambio" },
  { id: "fisher", label: "Efecto Fisher", group: "Tipo de cambio" },
  { id: "real-rate", label: "Tipo de cambio real", group: "Tipo de cambio" },
  { id: "derivatives-market", label: "Mercado de derivados", group: "Derivados" },
  { id: "derivative-instrument", label: "Concepto de instrumento financiero derivado", group: "Derivados" },
  { id: "forward-contracts", label: "Contratos a plazo", group: "Derivados" },
  { id: "forward", label: "Forward", group: "Derivados" },
  { id: "futures", label: "Futuros", group: "Derivados" },
  { id: "options", label: "Opciones", group: "Derivados" },
  { id: "closing-forward", label: "Cierre de posiciones a plazo", group: "Derivados" },
  { id: "forward-futures-diff", label: "Diferencias entre forwards y futuros", group: "Derivados" },
  { id: "fx-swaps", label: "Mención general de swaps en divisas", group: "Derivados" },
  { id: "currency-financial-crises", label: "Crisis cambiarias y financieras", group: "Crisis" },
  { id: "contemporary-currency-crises", label: "Crisis cambiarias contemporáneas", group: "Crisis" },
  { id: "contemporary-bop-crises", label: "Crisis de balanza de pagos contemporáneas", group: "Crisis" },
  { id: "international-cases", label: "Casos internacionales", group: "Casos" },
  { id: "china-rise", label: "Surgimiento económico de China", group: "Casos" },
  { id: "power-shift", label: "Cambio en el poder económico mundial", group: "Casos" },
  { id: "crisis-2008", label: "Crisis financiera de 2008", group: "Casos" },
  { id: "sovereign-debt-2010", label: "Crisis de deuda soberana de 2010", group: "Casos" },
  { id: "euro-problems", label: "Problemas del euro", group: "Casos" },
];

const COUNTRY_LIBRARY = {
  Mexico: {
    displayName: "México",
    accent: "#67efff",
    sources: {
      global: [
        {
          headline: "Banxico sube previsión del PIB para 2026 a 1.6%",
          source: "Yahoo Finanzas / El Universal",
          date: "27 feb 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/banxico-sube-previsi%C3%B3n-pib-2026-060000528.html",
          summary: "El banco central prevé crecimiento moderado y mantiene la atención en inflación, tasas e incertidumbre comercial.",
        },
        {
          headline: "El nearshoring sostiene la integración de México con Norteamérica",
          source: "Yahoo Finanzas / El Universal",
          date: "25 feb 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/m%C3%A9xico-registra-ied-hist%C3%B3rica-2025-110340336.html",
          summary: "La inversión extranjera directa alcanzó un máximo histórico, dato clave para explicar relocalización e integración productiva.",
        },
        {
          headline: "T-MEC y aranceles podrían impulsar economías regionales",
          source: "Yahoo Finanzas / El Universal",
          date: "29 dic 2025",
          url: "https://es-us.finanzas.yahoo.com/noticias/t-mec-aranceles-impulsar%C3%A1n-econom%C3%ADas-060000189.html",
          summary: "Banxico recoge expectativas empresariales sobre exportaciones, inversión y manufactura ante la revisión del acuerdo comercial.",
        },
      ],
      bop: [
        {
          headline: "La cuenta corriente mexicana cerró 2025 con superávit trimestral",
          source: "Yahoo Finanzas / El Universal",
          date: "26 nov 2025",
          url: "https://es-us.finanzas.yahoo.com/noticias/m%C3%A9xico-logra-super%C3%A1vit-corriente-060000012.html",
          summary: "La nota explica que la cuenta corriente registró superávit por exportaciones mayores a importaciones.",
        },
        {
          headline: "Las cuentas externas se fortalecen, reporta Banxico",
          source: "Yahoo Finanzas / El Universal",
          date: "26 feb 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/cuentas-externas-fortalecen-banxico-060000289.html",
          summary: "El déficit anual de cuenta corriente bajó a 0.4% del PIB, con apoyo de mercancías no petroleras e IED.",
        },
        {
          headline: "Banxico da a conocer datos de cuenta corriente de México",
          source: "Yahoo Finanzas / El Universal",
          date: "25 nov 2025",
          url: "https://es-us.finanzas.yahoo.com/noticias/banxico-datos-corriente-m%C3%A9xico-142916835.html",
          summary: "La balanza de pagos sirve para ver cómo se registran transacciones comerciales y financieras con el exterior.",
        },
      ],
      fx: [
        {
          headline: "El peso mexicano se hunde tras decisión sorpresiva de Banxico",
          source: "Expansión",
          date: "26 mar 2026",
          url: "https://expansion.mx/mercados/2026/03/26/peso-mexicano-hunde-decision-sorpresiva-banxico-bolsas-caen",
          summary: "La depreciación del peso tras el recorte de tasas muestra la relación entre política monetaria y tipo de cambio.",
        },
        {
          headline: "Banxico baja la tasa y cambia los incentivos del peso",
          source: "Yahoo Finanzas / Investing.com",
          date: "5 feb 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/banxico-inicia-2026-pausando-recortes-193715308.html",
          summary: "La pausa de Banxico en 7% ayuda a explicar el atractivo relativo del peso y los flujos hacia moneda local.",
        },
        {
          headline: "El superpeso arranca 2026 con fuerza frente al dólar",
          source: "Expansión",
          date: "13 ene 2026",
          url: "https://expansion.mx/mercados/2026/01/13/el-superpeso-arranca-2026-con-fuerza-y-el-dolar-cae-a-su-menor-nivel-en-18-meses",
          summary: "La apreciación inicial del peso permite discutir diferencial de tasas, dólar global y expectativas cambiarias.",
        },
      ],
      derivatives: [
        {
          headline: "Volatilidad del peso por conflicto en Medio Oriente: MexDer",
          source: "El Economista",
          date: "14 abr 2026",
          url: "https://www.eleconomista.com.mx/mercados/volatilidad-peso-conflicto-medio-oriente-mexder-20260414-808764.html",
          summary: "La nota explica por qué la volatilidad peso-dólar genera necesidad de coberturas con instrumentos derivados.",
        },
        {
          headline: "MexDer lista futuros y opciones de seis acciones de la BMV",
          source: "El Economista",
          date: "3 feb 2026",
          url: "https://www.eleconomista.com.mx/mercados/mexder-lista-futuros-opciones-seis-acciones-bmv-20260203-798258.html",
          summary: "El listado permite explicar futuros y opciones como instrumentos de cobertura e inversión en mercados organizados.",
        },
        {
          headline: "Swaps de TIIE de Fondeo logran récord en un entorno de tasas bajas",
          source: "El Economista",
          date: "12 ago 2025",
          url: "https://www.eleconomista.com.mx/mercados/swaps-tiie-fondeo-logran-record-entorno-tasas-bajas-20250812-772397.html",
          summary: "El volumen récord muestra cómo los swaps sirven para cubrir exposición a tasas de interés en México.",
        },
      ],
      crisis: [
        {
          headline: "Banco Mundial recorta PIB de México a 1.3% en 2026",
          source: "Yahoo Finanzas / El Universal",
          date: "14 ene 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/banco-mundial-recorta-pib-m%C3%A9xico-060000967.html",
          summary: "El ajuste refleja riesgos por la revisión del T-MEC, inversión débil y menor dinamismo económico.",
        },
        {
          headline: "Inflación en México se mantendrá cerca del 4% en 2026 y 2027",
          source: "Yahoo Finanzas / El Universal",
          date: "8 ene 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/inflaci%C3%B3n-m%C3%A9xico-mantendr%C3%A1-4-2026-171535737.html",
          summary: "La inflación persistente y las tasas altas ayudan a estudiar riesgos financieros y presión sobre crecimiento.",
        },
        {
          headline: "El peso se hunde tras recorte de Banxico y aumenta aversión al riesgo",
          source: "Expansión",
          date: "26 mar 2026",
          url: "https://expansion.mx/mercados/2026/03/26/peso-mexicano-hunde-decision-sorpresiva-banxico-bolsas-caen",
          summary: "La reacción cambiaria permite vincular tasas, confianza, riesgo país y posibles crisis financieras.",
        },
      ],
      cases: [
        {
          headline: "México registra IED histórica en 2025 con 40 mil 871 mdd",
          source: "Yahoo Finanzas / El Universal",
          date: "25 feb 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/m%C3%A9xico-registra-ied-hist%C3%B3rica-2025-110340336.html",
          summary: "El máximo de inversión extranjera ayuda a ubicar a México dentro del reordenamiento productivo mundial.",
        },
        {
          headline: "T-MEC y aranceles impulsarán economías regionales: Banxico",
          source: "Yahoo Finanzas / El Universal",
          date: "29 dic 2025",
          url: "https://es-us.finanzas.yahoo.com/noticias/t-mec-aranceles-impulsar%C3%A1n-econom%C3%ADas-060000189.html",
          summary: "La relación con Norteamérica muestra cómo cambian las cadenas de suministro ante tensiones con Asia.",
        },
        {
          headline: "Banxico ajusta su pronóstico de crecimiento para este año",
          source: "Yahoo Finanzas / El Universal",
          date: "26 feb 2026",
          url: "https://es-us.finanzas.yahoo.com/noticias/banxico-ajusta-pron%C3%B3stico-crecimiento-a%C3%B1o-140258640.html",
          summary: "El nuevo pronóstico permite comparar a México con otros casos internacionales de crecimiento moderado.",
        },
      ],
    },
  },
  "United States of America": {
    displayName: "Estados Unidos",
    accent: "#b8ff7a",
    sources: {
      global: {
        headline: "El FMI advierte sobre déficit fiscal, deuda y cuenta corriente de Estados Unidos",
        source: "FMI",
        date: "2 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/01/pr-26102-usa-imf-executive-board-concludes-2026-article-iv-consult",
        summary: "La consulta Article IV señala crecimiento resistente, deuda elevada y una posición externa más débil de lo deseable.",
      },
      bop: {
        headline: "El déficit de cuenta corriente de EE. UU. se redujo en el cuarto trimestre de 2025",
        source: "BEA",
        date: "25 mar 2026",
        url: "https://www.bea.gov/news/2026/us-international-transactions-and-investment-position-4th-quarter-and-year-2025",
        summary: "La BEA reportó que el déficit bajó a 190.7 mil millones de dólares, equivalente a 2.4% del PIB.",
      },
      fx: {
        headline: "La política comercial estadounidense vuelve a poner al dólar en el centro del ajuste externo",
        source: "Casa Blanca",
        date: "20 feb 2026",
        url: "https://www.whitehouse.gov/presidential-actions/2026/02/imposing-a-temporary-import-surcharge-to-address-fundamental-international-payments-problems/",
        summary: "La proclamación sobre recargos a importaciones menciona problemas de pagos internacionales y depreciación cambiaria.",
      },
      derivatives: {
        headline: "El FMI ve mercados ordenados, pero vulnerables por deuda, crédito privado y no bancarios",
        source: "FMI",
        date: "14 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/15/tr-04142026-press-briefing-transcript-global-financial-stability-report-spring-meetings-2026",
        summary: "La estabilidad financiera depende de liquidez, márgenes y cobertura de riesgos en mercados complejos.",
      },
      crisis: {
        headline: "La deuda pública y la cuenta corriente elevan el riesgo de rebalanceo externo desordenado",
        source: "FMI",
        date: "2 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/01/pr-26102-usa-imf-executive-board-concludes-2026-article-iv-consult",
        summary: "El FMI advierte que un cambio abrupto en preferencias de inversionistas extranjeros podría tensar el ajuste.",
      },
      cases: {
        headline: "La economía estadounidense sigue marcando las reglas financieras globales",
        source: "FMI",
        date: "2 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/01/pr-26102-usa-imf-executive-board-concludes-2026-article-iv-consult",
        summary: "Dólar, bonos del Tesoro y política monetaria siguen funcionando como referencias del sistema internacional.",
      },
    },
  },
  China: {
    displayName: "China",
    accent: "#ffcc66",
    sources: {
      global: {
        headline: "China creció 5% en el primer trimestre de 2026 pese a choques de energía y cadenas de suministro",
        source: "China Briefing",
        date: "17 abr 2026",
        url: "https://www.china-briefing.com/news/chinas-q1-2026-gdp/",
        summary: "El crecimiento se apoyó en industria, exportaciones y gasto fiscal, con consumo interno todavía débil.",
      },
      bop: {
        headline: "Exportaciones e industria vuelven a impulsar la posición externa china",
        source: "China Briefing",
        date: "24 mar 2026",
        url: "https://www.china-briefing.com/news/chinas-economy-in-2026-january-february-rebound/",
        summary: "El arranque de 2026 mostró comercio exterior fuerte y alta inversión tecnológica.",
      },
      fx: {
        headline: "El FMI elevó la previsión de crecimiento de China por estímulos y tregua comercial",
        source: "South China Morning Post",
        date: "19 ene 2026",
        url: "https://www.scmp.com/economy/china-economy/article/3340419/imf-raises-chinas-2026-growth-forecast-45-citing-us-truce-and-stimulus-roll-out",
        summary: "El tipo de cambio y la política macro se leen dentro de la relación yuan-dólar y la demanda global.",
      },
      derivatives: {
        headline: "La volatilidad de energía y cadenas de suministro aumenta la necesidad de coberturas comerciales",
        source: "China Briefing",
        date: "17 abr 2026",
        url: "https://www.china-briefing.com/news/chinas-q1-2026-gdp/",
        summary: "Empresas exportadoras enfrentan precios, divisas y logística, terreno típico para derivados.",
      },
      crisis: {
        headline: "La demanda interna débil sigue siendo el riesgo central del rebote chino",
        source: "China Briefing",
        date: "17 abr 2026",
        url: "https://www.china-briefing.com/news/chinas-q1-2026-gdp/",
        summary: "El caso muestra cómo una economía grande puede crecer y aun así transmitir riesgos al sistema global.",
      },
      cases: {
        headline: "El ascenso chino se sostiene en industria, tecnología y comercio exterior",
        source: "China Briefing",
        date: "24 mar 2026",
        url: "https://www.china-briefing.com/news/chinas-economy-in-2026-january-february-rebound/",
        summary: "Es el país clave para explicar el cambio en el poder económico mundial.",
      },
    },
  },
  Germany: {
    displayName: "Alemania",
    accent: "#ff8f70",
    sources: {
      global: {
        headline: "El pronóstico conjunto alemán ve recuperación frágil por energía, defensa e incertidumbre comercial",
        source: "ifo Institute",
        date: "1 abr 2026",
        url: "https://www.ifo.de/en/facts/2026-04-01/joint-economic-forecast-spring-2026-energy-price-shock-overshadows-fiscal-stimulus",
        summary: "La economía se apoya más en demanda interna e inversión pública que en el viejo motor exportador.",
      },
      bop: {
        headline: "El superávit externo de la zona euro cayó en 2025",
        source: "Banco Central Europeo",
        date: "9 abr 2026",
        url: "https://www.ecb.europa.eu/press/stats/bop/2026/html/ecb.bq260409~16fc82b973.en.html",
        summary: "El BCE reportó un superávit de cuenta corriente de 276 mil millones de euros, menor al del año anterior.",
      },
      fx: {
        headline: "La zona euro enfrenta presiones de inflación energética y política fiscal",
        source: "Wall Street Journal",
        date: "21 abr 2026",
        url: "https://www.wsj.com/economy/central-banking/governments-could-force-ecbs-hand-if-energy-support-is-too-broad-lagarde-says-d6099711",
        summary: "El euro se analiza con inflación, tasas del BCE y apoyo fiscal ante energía cara.",
      },
      derivatives: {
        headline: "El BCE registra grandes flujos de cartera entre residentes y no residentes",
        source: "Banco Central Europeo",
        date: "17 abr 2026",
        url: "https://www.ecb.europa.eu/press/stats/bop/2026/html/ecb.bp260417~8cf2910734.hr.html",
        summary: "Los flujos financieros transfronterizos son la base para hablar de coberturas, swaps y derivados.",
      },
      crisis: {
        headline: "El FMI advierte que deuda y energía elevan la sensibilidad de los mercados",
        source: "The Guardian",
        date: "15 abr 2026",
        url: "https://www.theguardian.com/business/2026/apr/15/iran-war-global-debt-imf-prices-growth",
        summary: "Alemania ayuda a conectar estabilidad europea con riesgos de deuda soberana.",
      },
      cases: {
        headline: "El modelo exportador alemán pierde fuerza frente a una economía mundial más fragmentada",
        source: "ifo Institute",
        date: "1 abr 2026",
        url: "https://www.ifo.de/en/facts/2026-04-01/joint-economic-forecast-spring-2026-energy-price-shock-overshadows-fiscal-stimulus",
        summary: "Sirve para comparar la globalización industrial clásica con el nuevo ciclo geopolítico.",
      },
    },
  },
  Japan: {
    displayName: "Japón",
    accent: "#f5a7ff",
    sources: {
      global: {
        headline: "El FMI destaca resiliencia de Japón, pero prevé moderación del crecimiento en 2026",
        source: "FMI",
        date: "3 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/02/pr-26105-japan-imf-executive-board-concludes-2026-article-iv-consult",
        summary: "La economía crece sobre potencial, con salarios al alza, inflación y riesgos externos.",
      },
      bop: {
        headline: "Japón mantiene un superávit de cuenta corriente apoyado en ingresos de activos externos",
        source: "FMI",
        date: "13 feb 2026",
        url: "https://www.imf.org/en/news/articles/2026/02/13/imf-cs-02172026-japan-staff-concluding-statement-of-the-2026-article-iv-mission",
        summary: "El FMI subraya la importancia de la posición neta de inversión internacional japonesa.",
      },
      fx: {
        headline: "Japón considera que una política del BOJ que fortalezca el yen podría ayudar contra la inflación",
        source: "The Japan Times / Reuters",
        date: "12 abr 2026",
        url: "https://www.japantimes.co.jp/business/2026/04/12/economy/akazawa-boj-policy-inflation/",
        summary: "La noticia conecta tasas, inflación importada y tipo de cambio yen-dólar.",
      },
      derivatives: {
        headline: "El FMI observa exposición cambiaria y riesgos de valuación en el sistema financiero japonés",
        source: "FMI",
        date: "3 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/02/pr-26105-japan-imf-executive-board-concludes-2026-article-iv-consult",
        summary: "Las coberturas de divisas y tasas son relevantes para bancos, aseguradoras y exportadores.",
      },
      crisis: {
        headline: "La deuda pública y los rendimientos de bonos japoneses siguen bajo vigilancia",
        source: "FMI",
        date: "13 feb 2026",
        url: "https://www.imf.org/en/news/articles/2026/02/13/imf-cs-02172026-japan-staff-concluding-statement-of-the-2026-article-iv-mission",
        summary: "Japón permite discutir crisis financieras sin default, por su deuda alta y grandes activos externos.",
      },
      cases: {
        headline: "Japón muestra cómo una economía avanzada se adapta a inflación, envejecimiento y shocks externos",
        source: "FMI",
        date: "3 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/02/pr-26105-japan-imf-executive-board-concludes-2026-article-iv-consult",
        summary: "Es un caso útil para comparar política monetaria gradual y tipo de cambio flexible.",
      },
    },
  },
  "United Kingdom": {
    displayName: "Inglaterra / Reino Unido",
    accent: "#9fb7ff",
    sources: {
      global: {
        headline: "El Reino Unido roza la recesión ante el shock energético y geopolítico",
        source: "The Guardian",
        date: "20 abr 2026",
        url: "https://www.theguardian.com/business/2026/apr/20/250000-could-lose-job-2027-uk-recession-analysis-economy-iran-war",
        summary: "El análisis apunta a menor crecimiento, desempleo al alza y cautela de empresas.",
      },
      bop: {
        headline: "El Banco de Inglaterra alerta sobre deuda soberana, bonos y financiamiento de mercado",
        source: "Bank of England",
        date: "1 abr 2026",
        url: "https://www.bankofengland.co.uk/financial-policy-committee-record/2026/april-2026",
        summary: "El reporte conecta flujos financieros, tasas largas y vulnerabilidades de mercado.",
      },
      fx: {
        headline: "La libra retrocede desde máximos de ocho semanas por expectativas del Banco de Inglaterra",
        source: "Trading Economics",
        date: "16 abr 2026",
        url: "https://tradingeconomics.com/united-kingdom/currency/news/542453",
        summary: "La noticia permite leer el tipo de cambio con inflación, tasas y expectativas.",
      },
      derivatives: {
        headline: "El Banco de Inglaterra mantiene el foco en fondos, repos, crédito privado y resiliencia de mercado",
        source: "Bank of England",
        date: "1 abr 2026",
        url: "https://www.bankofengland.co.uk/financial-policy-committee-record/2026/april-2026",
        summary: "Es un puente directo hacia derivados, márgenes, liquidez y cierre de posiciones.",
      },
      crisis: {
        headline: "El FPC advierte que varios riesgos podrían cristalizar al mismo tiempo",
        source: "Bank of England",
        date: "1 abr 2026",
        url: "https://www.bankofengland.co.uk/financial-policy-committee-record/2026/april-2026",
        summary: "El Reino Unido recuerda cómo un shock puede pasar de bonos a bancos y hogares.",
      },
      cases: {
        headline: "La libra y los gilt siguen siendo caso de estudio tras el estrés financiero de 2022",
        source: "Bank of England",
        date: "1 abr 2026",
        url: "https://www.bankofengland.co.uk/financial-policy-committee-record/2026/april-2026",
        summary: "El banco central usa ese antecedente para explicar vigilancia de mercados no bancarios.",
      },
    },
  },
  Australia: {
    displayName: "Australia",
    accent: "#70d6ff",
    sources: {
      global: {
        headline: "El FMI advierte que el shock energético global amenaza la recuperación australiana",
        source: "The Guardian / FMI",
        date: "14 abr 2026",
        url: "https://www.theguardian.com/business/2026/apr/14/imf-world-economic-outlook-energy-crisis-global-recession-australia-fuel",
        summary: "El reporte conecta el encarecimiento de energía con menor crecimiento, inflación y decisiones fiscales en Australia.",
      },
      bop: {
        headline: "El déficit de cuenta corriente australiano se amplió a 21.1 mil millones de dólares australianos",
        source: "Australian Bureau of Statistics",
        date: "3 mar 2026",
        url: "https://www.abs.gov.au/media-centre/media-releases/current-account-deficit-widens",
        summary: "La caída se explica por un mayor déficit de renta primaria y un superávit comercial casi estable.",
      },
      fx: {
        headline: "El RBA explica cómo el comercio de recursos y los flujos de capital moldean la balanza de pagos",
        source: "Reserve Bank of Australia",
        date: "2026",
        url: "https://www.rba.gov.au/education/resources/explainers/trends-in-australias-balance-of-payments.html",
        summary: "Australia es un ejemplo claro de tipo de cambio ligado a commodities, inversión extranjera y términos de intercambio.",
      },
      derivatives: {
        headline: "Exportadores australianos enfrentan precios de energía, minerales y tipo de cambio",
        source: "Australian Bureau of Statistics",
        date: "3 mar 2026",
        url: "https://www.abs.gov.au/statistics/economy/international-trade/balance-payments-and-international-investment-position-australia/latest-release",
        summary: "La exposición a recursos naturales vuelve relevantes futuros, forwards y opciones para cubrir ingresos en divisas.",
      },
      crisis: {
        headline: "El FMI advierte que un shock petrolero severo podría arrastrar a la economía global",
        source: "The Guardian / FMI",
        date: "14 abr 2026",
        url: "https://www.theguardian.com/business/2026/apr/14/imf-world-economic-outlook-energy-crisis-global-recession-australia-fuel",
        summary: "Australia permite analizar cómo una economía abierta recibe choques externos desde energía y comercio.",
      },
      cases: {
        headline: "Australia combina recursos, inversión extranjera y Asia como eje de inserción global",
        source: "Reserve Bank of Australia",
        date: "2026",
        url: "https://www.rba.gov.au/education/resources/explainers/trends-in-australias-balance-of-payments.html",
        summary: "Sirve para explicar globalización desde materias primas, capital extranjero y vínculos con China.",
      },
    },
  },
  Canada: {
    displayName: "Canadá",
    accent: "#ff7070",
    sources: {
      global: {
        headline: "Empresas canadienses reportan mejor ánimo, pero costos de energía y comercio siguen pesando",
        source: "Bank of Canada",
        date: "20 abr 2026",
        url: "https://www.bankofcanada.ca/publications/mpr/mpr-2026-01-28/canadian-conditions/",
        summary: "El banco central observa crecimiento débil, efectos de aranceles de EE. UU. y volatilidad financiera.",
      },
      bop: {
        headline: "Canadá registró déficit de cuenta corriente de 700 millones de dólares canadienses en Q4 2025",
        source: "Trading Economics",
        date: "abr 2026",
        url: "https://tradingeconomics.com/canada/current-account",
        summary: "El dato ayuda a leer exportaciones, importaciones, ingresos externos y financiamiento internacional.",
      },
      fx: {
        headline: "El dólar canadiense ronda 72 centavos de dólar estadounidense",
        source: "Bank of Canada",
        date: "ene 2026",
        url: "https://www.bankofcanada.ca/publications/mpr/mpr-2026-01-28/canadian-conditions/",
        summary: "El informe vincula la moneda canadiense con condiciones financieras, petróleo, tasas y comercio con EE. UU.",
      },
      derivatives: {
        headline: "El Bank of Canada señala volatilidad financiera por eventos geopolíticos",
        source: "Bank of Canada",
        date: "20 abr 2026",
        url: "https://www.bankofcanada.ca/",
        summary: "La exposición a energía, tasas y dólar estadounidense vuelve útiles las coberturas cambiarias y de commodities.",
      },
      crisis: {
        headline: "Hogares canadienses esperan que el conflicto en Medio Oriente suba precios y debilite la economía",
        source: "Bank of Canada",
        date: "20 abr 2026",
        url: "https://www.bankofcanada.ca/",
        summary: "El caso muestra cómo un shock global puede filtrarse a inflación, expectativas y consumo.",
      },
      cases: {
        headline: "Canadá muestra interdependencia extrema con Estados Unidos por comercio, energía y tipo de cambio",
        source: "Bank of Canada",
        date: "ene 2026",
        url: "https://www.bankofcanada.ca/publications/mpr/mpr-2026-01-28/canadian-conditions/",
        summary: "Es útil para comparar integración regional con vulnerabilidad ante aranceles.",
      },
    },
  },
  "South Korea": {
    displayName: "Corea del Sur",
    accent: "#b4f8ff",
    sources: {
      global: {
        headline: "Corea del Sur habría vuelto al crecimiento en Q1 gracias a semiconductores",
        source: "Reuters / WSAU",
        date: "21 abr 2026",
        url: "https://wsau.com/2026/04/20/south-korea-economy-likely-returned-to-growth-in-q1-reuters-poll/",
        summary: "Una encuesta de Reuters prevé crecimiento trimestral de 1.0%, impulsado por chips y demanda doméstica.",
      },
      bop: {
        headline: "Los semiconductores siguen siendo el motor exportador coreano",
        source: "Reuters / WSAU",
        date: "21 abr 2026",
        url: "https://wsau.com/2026/04/20/south-korea-economy-likely-returned-to-growth-in-q1-reuters-poll/",
        summary: "El caso permite conectar balanza comercial, cuenta corriente y ciclos tecnológicos globales.",
      },
      fx: {
        headline: "La economía coreana queda expuesta al won, chips y tensión geopolítica",
        source: "Reuters / WSAU",
        date: "21 abr 2026",
        url: "https://wsau.com/2026/04/20/south-korea-economy-likely-returned-to-growth-in-q1-reuters-poll/",
        summary: "El tipo de cambio se interpreta con exportaciones, tasas globales y riesgo regional.",
      },
      derivatives: {
        headline: "Inversionistas vuelven a acciones coreanas por expectativas de utilidades en chips",
        source: "Barron's",
        date: "21 abr 2026",
        url: "https://www.barrons.com/articles/kospi-index-sk-hynix-stock-samsung-record-f8037144",
        summary: "La volatilidad de acciones, won y comercio tecnológico da pie a opciones, futuros y cobertura de cartera.",
      },
      crisis: {
        headline: "La guerra en Medio Oriente podría empezar a pesar sobre la actividad coreana",
        source: "Reuters / WSAU",
        date: "21 abr 2026",
        url: "https://wsau.com/2026/04/20/south-korea-economy-likely-returned-to-growth-in-q1-reuters-poll/",
        summary: "Corea del Sur ilustra cómo una economía exportadora puede sufrir shocks externos aunque su sector líder crezca.",
      },
      cases: {
        headline: "Corea del Sur gana peso global por memoria, IA y cadenas de suministro",
        source: "Barron's",
        date: "21 abr 2026",
        url: "https://www.barrons.com/articles/kospi-index-sk-hynix-stock-samsung-record-f8037144",
        summary: "Es un caso actual de cambio de poder económico por tecnología y manufactura avanzada.",
      },
    },
  },
  "North Korea": {
    displayName: "Corea del Norte",
    accent: "#d3d7de",
    sources: {
      global: {
        headline: "China y Rusia impulsan señales de recuperación económica en Corea del Norte",
        source: "Euronews",
        date: "17 abr 2026",
        url: "https://www.euronews.com/2026/04/17/china-and-russia-ties-driving-north-korean-economic-recovery-seoul-ministry-says",
        summary: "El ministerio surcoreano señala que el acercamiento a Moscú y Pekín sostiene comercio y actividad bajo sanciones.",
      },
      bop: {
        headline: "Las sanciones hacen opaca la balanza externa norcoreana",
        source: "Euronews",
        date: "17 abr 2026",
        url: "https://www.euronews.com/2026/04/17/china-and-russia-ties-driving-north-korean-economic-recovery-seoul-ministry-says",
        summary: "La noticia permite hablar de transacciones registradas, comercio informal y límites de medición estadística.",
      },
      fx: {
        headline: "Corea del Norte opera fuera de los mercados cambiarios normales por sanciones y controles",
        source: "Euronews",
        date: "17 abr 2026",
        url: "https://www.euronews.com/2026/04/17/china-and-russia-ties-driving-north-korean-economic-recovery-seoul-ministry-says",
        summary: "Es un contraste útil frente a países con divisas convertibles y bancos centrales transparentes.",
      },
      derivatives: {
        headline: "El aislamiento financiero impide mercados de derivados profundos y transparentes",
        source: "Euronews",
        date: "17 abr 2026",
        url: "https://www.euronews.com/2026/04/17/china-and-russia-ties-driving-north-korean-economic-recovery-seoul-ministry-says",
        summary: "Corea del Norte funciona como caso límite para explicar por qué los derivados requieren mercado, confianza y reglas.",
      },
      crisis: {
        headline: "La IAEA advierte que Corea del Norte expande rápidamente su capacidad nuclear",
        source: "The Guardian",
        date: "15 abr 2026",
        url: "https://www.theguardian.com/world/2026/apr/15/north-korea-nuclear-weapons-capability-un-watchdog-rafael-grossi",
        summary: "El riesgo geopolítico se cruza con sanciones, comercio restringido y estabilidad financiera regional.",
      },
      cases: {
        headline: "Corea del Norte muestra una globalización restringida por sanciones, seguridad y alianzas",
        source: "Euronews",
        date: "17 abr 2026",
        url: "https://www.euronews.com/2026/04/17/china-and-russia-ties-driving-north-korean-economic-recovery-seoul-ministry-says",
        summary: "Sirve para comparar integración abierta con dependencia política de pocos socios.",
      },
    },
  },
  Italy: {
    displayName: "Italia",
    accent: "#91f0b6",
    sources: {
      global: {
        headline: "El FMI prevé menor déficit italiano, pero deuda pública al alza",
        source: "ANSA / FMI",
        date: "15 abr 2026",
        url: "https://www.ansa.it/english/news/business/2026/04/15/imf-says-italy-deficit-to-fall-to-2.8-in-2026-debt-to-rise-to-138.4_be30e5cc-3202-402c-b23a-5610b28dc3a8.html",
        summary: "El FMI estima déficit de 2.8% del PIB en 2026 y deuda de 138.4%, con énfasis en productividad.",
      },
      bop: {
        headline: "El FMI señaló que la cuenta corriente italiana se fortaleció a superávit superior a 1% del PIB",
        source: "FMI",
        date: "28 may 2025",
        url: "https://www.imf.org/en/news/articles/2025/05/28/05282025-mcs-italy-staff-concluding-statement-of-the-2025-article-iv-mission",
        summary: "El dato ayuda a conectar exportaciones, servicios, renta externa y posición dentro de la eurozona.",
      },
      fx: {
        headline: "Italia comparte el dilema del euro: deuda, inflación y política del BCE",
        source: "Euronews / FMI",
        date: "14 abr 2026",
        url: "https://www.euronews.com/business/2026/04/14/imf-drops-eurozones-economic-growth-forecast-to-11-from-14-amid-iran-war",
        summary: "Como miembro del euro, no ajusta con moneda propia; depende de competitividad, BCE y política fiscal.",
      },
      derivatives: {
        headline: "La relación entre deuda soberana y bancos sigue siendo foco de estabilidad financiera en Italia",
        source: "FMI",
        date: "28 may 2025",
        url: "https://www.imf.org/en/news/articles/2025/05/28/05282025-mcs-italy-staff-concluding-statement-of-the-2025-article-iv-mission",
        summary: "Riesgo soberano, bonos y bancos conectan con derivados de tasas, crédito y cobertura de cartera.",
      },
      crisis: {
        headline: "La deuda italiana vuelve a crecer pese a menor déficit",
        source: "ANSA / FMI",
        date: "15 abr 2026",
        url: "https://www.ansa.it/english/news/business/2026/04/15/imf-says-italy-deficit-to-fall-to-2.8-in-2026-debt-to-rise-to-138.4_be30e5cc-3202-402c-b23a-5610b28dc3a8.html",
        summary: "Italia es central para explicar crisis de deuda soberana y problemas del euro.",
      },
      cases: {
        headline: "Italia combina euro, alto endeudamiento y bajo crecimiento de productividad",
        source: "ANSA / FMI",
        date: "15 abr 2026",
        url: "https://www.ansa.it/english/news/business/2026/04/15/imf-says-italy-deficit-to-fall-to-2.8-in-2026-debt-to-rise-to-138.4_be30e5cc-3202-402c-b23a-5610b28dc3a8.html",
        summary: "Es un caso perfecto para la deuda soberana de 2010 y los límites de una unión monetaria.",
      },
    },
  },
  Russia: {
    displayName: "Rusia",
    accent: "#d6b2ff",
    sources: {
      global: {
        headline: "El FMI elevó la previsión de crecimiento de Rusia a 1.1% por precios de petróleo más altos",
        source: "Reuters / Investing.com",
        date: "14 abr 2026",
        url: "https://www.investing.com/news/economy-news/imf-raises-russia-2026-gdp-growth-forecast-to-11-on-higher-oil-prices-4613306",
        summary: "El alza de commodities mejora el pronóstico, pero sanciones, guerra y tasas altas siguen frenando la economía.",
      },
      bop: {
        headline: "Rusia absorbe costos extra de importación por sanciones y rutas comerciales alternativas",
        source: "Business Insider",
        date: "17 abr 2026",
        url: "https://www.businessinsider.com/russia-spend-130-billion-buy-goods-sanctioned-latvia-analysis-2026-4",
        summary: "El reporte estima costos adicionales de 130 mil millones de dólares para adquirir bienes bajo sanciones.",
      },
      fx: {
        headline: "El rublo queda condicionado por petróleo, sanciones y política monetaria restrictiva",
        source: "Reuters / Investing.com",
        date: "16 abr 2026",
        url: "https://www.investing.com/news/economy-news/russia-looks-for-a-way-out-of-its-sharpest-economic-contraction-in-three-years-4618290",
        summary: "La contracción y las tasas de dos dígitos muestran cómo el tipo de cambio se cruza con guerra y controles financieros.",
      },
      derivatives: {
        headline: "Sanciones y commodities elevan la importancia de coberturas fuera de mercados occidentales",
        source: "Business Insider",
        date: "17 abr 2026",
        url: "https://www.businessinsider.com/russia-spend-130-billion-buy-goods-sanctioned-latvia-analysis-2026-4",
        summary: "Rusia sirve para explicar cómo se encarece la gestión de riesgo cuando una economía pierde acceso financiero normal.",
      },
      crisis: {
        headline: "Rusia busca salir de su contracción económica más fuerte en tres años",
        source: "Reuters / Investing.com",
        date: "16 abr 2026",
        url: "https://www.investing.com/news/economy-news/russia-looks-for-a-way-out-of-its-sharpest-economic-contraction-in-three-years-4618290",
        summary: "El caso combina sanciones, gasto militar, inflación, tasas altas y vulnerabilidad externa.",
      },
      cases: {
        headline: "Rusia muestra cómo energía, guerra y sanciones reordenan las finanzas internacionales",
        source: "Reuters / Investing.com",
        date: "14 abr 2026",
        url: "https://www.investing.com/news/economy-news/imf-raises-russia-2026-gdp-growth-forecast-to-11-on-higher-oil-prices-4613306",
        summary: "Es un caso actual para discutir fragmentación financiera y comercio por bloques.",
      },
    },
  },
  Africa: {
    displayName: "África",
    accent: "#9fb8ca",
    sources: {
      global: {
        headline: "El FMI advierte que África enfrenta rebaja de crecimiento por la guerra en Medio Oriente",
        source: "African Business / FMI",
        date: "15 abr 2026",
        url: "https://imf.african.business/2026/04/trade-investment/imf-says-africa-faces-growth-downgrade-amid-middle-east-war",
        summary: "El shock energético, inflación y menor ayuda externa reducen el impulso regional previsto para 2026 y 2027.",
      },
      bop: {
        headline: "El FMI dice que las cuentas corrientes africanas mejoraron en 2025, pero el shock externo presiona de nuevo",
        source: "FMI",
        date: "16 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/16/tr-04162026-press-briefing-transcript-african-department-spring-meetings-2026",
        summary: "El informe menciona mejores balances externos en 2025 y nuevas presiones por energía, transporte, turismo y remesas.",
      },
      fx: {
        headline: "El FMI destaca realineamientos cambiarios y reformas monetarias en economías africanas",
        source: "FMI",
        date: "16 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/16/tr-04162026-press-briefing-transcript-african-department-spring-meetings-2026",
        summary: "Ethiopía y Nigeria aparecen como ejemplos de ajustes cambiarios, reducción de subsidios y política monetaria más sólida.",
      },
      derivatives: {
        headline: "La nueva deuda africana migra hacia mercados domésticos y moneda local",
        source: "FMI Finance & Development",
        date: "mar 2026",
        url: "https://www.imf.org/publications/fandd/issues/2026/03/the-new-face-of-african-debt-amadou-sy",
        summary: "El cambio reduce algunos riesgos de divisa, pero aumenta retos de tasas, liquidez y profundidad de mercados financieros.",
      },
      crisis: {
        headline: "El FMI ve las ganancias de estabilización africanas bajo presión por energía, alimentos y financiamiento",
        source: "FMI",
        date: "16 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/16/tr-04162026-press-briefing-transcript-african-department-spring-meetings-2026",
        summary: "La región creció 4.5% en 2025, pero el pronóstico 2026 bajó a 4.3% y la inflación mediana subiría a 5%.",
      },
      cases: {
        headline: "África muestra cómo deuda, ayuda externa, energía y divisas se cruzan en economías emergentes",
        source: "FMI Finance & Development",
        date: "mar 2026",
        url: "https://www.imf.org/publications/fandd/issues/2026/03/the-new-face-of-african-debt-amadou-sy",
        summary: "El continente sirve como bloque para estudiar vulnerabilidad externa sin separar país por país.",
      },
    },
  },
  India: {
    displayName: "India",
    accent: "#8bffb3",
    sources: {
      global: {
        headline: "India y Corea del Sur buscan llevar su comercio bilateral a 50 mil millones de dólares",
        source: "Associated Press",
        date: "20 abr 2026",
        url: "https://apnews.com/article/8453d27375d5013d095c9b5febcfbdfc",
        summary: "El acuerdo apunta a cadenas de suministro, tecnología, inversión y acceso a mercados.",
      },
      bop: {
        headline: "Las exportaciones de joyería india resisten, aunque caen en dólares",
        source: "The Economic Times",
        date: "16 abr 2026",
        url: "https://m.economictimes.com/news/economy/foreign-trade/india-gem-and-jewellery-exports-rise-to-2-44-lakh-crore-in-fy26-amid-global-headwinds/articleshow/130281220.cms",
        summary: "El dato sirve para distinguir valores en moneda local y en dólares dentro de la balanza externa.",
      },
      fx: {
        headline: "El RBI relajó parcialmente restricciones sobre derivados de la rupia",
        source: "Times of India",
        date: "20 abr 2026",
        url: "https://timesofindia.indiatimes.com/business/india-business/rbi-partially-rolls-back-curbs-on-rupee-derivative-trades/articleshow/130405612.cms",
        summary: "La medida busca normalizar liquidez en derivados cambiarios tras volatilidad de la rupia.",
      },
      derivatives: {
        headline: "La reapertura parcial de derivados de la rupia devuelve profundidad al mercado",
        source: "Times of India",
        date: "20 abr 2026",
        url: "https://timesofindia.indiatimes.com/business/india-business/rbi-partially-rolls-back-curbs-on-rupee-derivative-trades/articleshow/130405612.cms",
        summary: "Es el ejemplo más directo para forwards, futuros, opciones y coberturas de divisas.",
      },
      crisis: {
        headline: "La rupia muestra cómo una moneda emergente puede forzar medidas temporales de mercado",
        source: "Times of India",
        date: "20 abr 2026",
        url: "https://timesofindia.indiatimes.com/business/india-business/rbi-partially-rolls-back-curbs-on-rupee-derivative-trades/articleshow/130405612.cms",
        summary: "La noticia conecta volatilidad cambiaria con regulación financiera.",
      },
      cases: {
        headline: "India refuerza su papel en cadenas asiáticas de tecnología y manufactura",
        source: "Associated Press",
        date: "20 abr 2026",
        url: "https://apnews.com/article/8453d27375d5013d095c9b5febcfbdfc",
        summary: "El caso muestra el desplazamiento del poder económico hacia Asia.",
      },
    },
  },
  Brazil: {
    displayName: "Brasil",
    accent: "#a9d6bf",
    sources: {
      global: {
        headline: "El real brasileño se acerca a máximos de casi dos años",
        source: "Trading Economics",
        date: "2 abr 2026",
        url: "https://tradingeconomics.com/brazil/currency/news/538853",
        summary: "La moneda se apoya en commodities, tasas reales altas y postura del banco central.",
      },
      bop: {
        headline: "Commodities y entradas de dólares sostienen a Brasil en el shock global",
        source: "Trading Economics",
        date: "2 abr 2026",
        url: "https://tradingeconomics.com/brazil/currency/news/538853",
        summary: "El petróleo, soya y mineral de hierro explican parte de los flujos externos.",
      },
      fx: {
        headline: "El real se beneficia de commodities y de un banco central todavía restrictivo",
        source: "Trading Economics",
        date: "2 abr 2026",
        url: "https://tradingeconomics.com/brazil/currency/news/538853",
        summary: "Sirve para explicar tipo de cambio real, tasas e inflación esperada.",
      },
      derivatives: {
        headline: "Exportadores brasileños enfrentan precios de commodities y riesgo cambiario",
        source: "Trading Economics",
        date: "2 abr 2026",
        url: "https://tradingeconomics.com/brazil/currency/news/538853",
        summary: "La exposición de exportadores vuelve naturales las coberturas con futuros y forwards.",
      },
      crisis: {
        headline: "Brasil muestra cómo un shock externo puede fortalecer o debilitar a emergentes según sus exportaciones",
        source: "Trading Economics",
        date: "2 abr 2026",
        url: "https://tradingeconomics.com/brazil/currency/news/538853",
        summary: "El caso contrasta con países importadores de energía.",
      },
      cases: {
        headline: "Brasil gana relevancia por alimentos, energía y minerales en la economía global",
        source: "Trading Economics",
        date: "2 abr 2026",
        url: "https://tradingeconomics.com/brazil/currency/news/538853",
        summary: "Es útil para analizar poder económico desde recursos naturales y monedas emergentes.",
      },
    },
  },
  Argentina: {
    displayName: "Argentina",
    accent: "#7ef2ff",
    sources: {
      global: {
        headline: "Argentina alcanza acuerdo técnico con el FMI para liberar cerca de mil millones de dólares",
        source: "FMI",
        date: "15 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/15/pr-26120-argentina-imf-reaches-agreement-on-2nd-rev-under-eff-arrangement",
        summary: "El programa busca sostener desinflación, estabilidad externa, reservas y acceso a mercados.",
      },
      bop: {
        headline: "El FMI proyecta acumulación de reservas netas para Argentina en 2026",
        source: "FMI",
        date: "15 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/15/pr-26120-argentina-imf-reaches-agreement-on-2nd-rev-under-eff-arrangement",
        summary: "El objetivo de reservas explica por qué la balanza de pagos importa en crisis recurrentes.",
      },
      fx: {
        headline: "Argentina ajusta su marco monetario y cambiario dentro del programa con el FMI",
        source: "FMI",
        date: "15 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/15/pr-26120-argentina-imf-reaches-agreement-on-2nd-rev-under-eff-arrangement",
        summary: "El comunicado menciona bandas cambiarias más amplias y política monetaria restrictiva.",
      },
      derivatives: {
        headline: "El financiamiento en dólares y la volatilidad del peso vuelven clave la gestión de coberturas",
        source: "FMI",
        date: "15 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/15/pr-26120-argentina-imf-reaches-agreement-on-2nd-rev-under-eff-arrangement",
        summary: "La deuda en moneda extranjera y los flujos de capital conectan con forwards y swaps.",
      },
      crisis: {
        headline: "Argentina sigue siendo caso contemporáneo de crisis externa, deuda y credibilidad",
        source: "FMI",
        date: "15 abr 2026",
        url: "https://www.imf.org/en/news/articles/2026/04/15/pr-26120-argentina-imf-reaches-agreement-on-2nd-rev-under-eff-arrangement",
        summary: "El programa intenta reconstruir reservas y acceso sostenible al mercado internacional.",
      },
      cases: {
        headline: "Argentina es el mayor deudor del FMI y un caso vivo de estabilización externa",
        source: "MercoPress / Reuters",
        date: "15 abr 2026",
        url: "https://en.mercopress.com/2026/04/15/imf-approves-second-review-of-argentina-program-unlocking-us-1-billion-disbursement",
        summary: "El caso conecta deuda soberana, moneda, reservas y reformas estructurales.",
      },
    },
  },
  France: {
    displayName: "Francia / Eurozona",
    accent: "#c7fffd",
    sources: {
      global: {
        headline: "La eurozona mantiene superávit externo, pero menor que el año anterior",
        source: "Banco Central Europeo",
        date: "17 abr 2026",
        url: "https://www.ecb.europa.eu/press/stats/bop/2026/html/ecb.bp260417~8cf2910734.hr.html",
        summary: "El BCE reportó superávit de cuenta corriente de 25 mil millones de euros en febrero.",
      },
      bop: {
        headline: "La balanza de pagos trimestral de la eurozona muestra menor superávit en 2025",
        source: "Banco Central Europeo",
        date: "9 abr 2026",
        url: "https://www.ecb.europa.eu/press/stats/bop/2026/html/ecb.bq260409~16fc82b973.en.html",
        summary: "El superávit anual bajó de 2.7% a 1.7% del PIB de la zona euro.",
      },
      fx: {
        headline: "Lagarde advierte que apoyos energéticos amplios podrían obligar al BCE a endurecer tasas",
        source: "Wall Street Journal",
        date: "21 abr 2026",
        url: "https://www.wsj.com/economy/central-banking/governments-could-force-ecbs-hand-if-energy-support-is-too-broad-lagarde-says-d6099711",
        summary: "El euro depende de la mezcla entre inflación energética, política fiscal y tasas del BCE.",
      },
      derivatives: {
        headline: "Los flujos de cartera de la eurozona superan cientos de miles de millones de euros",
        source: "Banco Central Europeo",
        date: "17 abr 2026",
        url: "https://www.ecb.europa.eu/press/stats/bop/2026/html/ecb.bp260417~8cf2910734.hr.html",
        summary: "La escala de los flujos justifica coberturas de divisas, tasas y portafolio.",
      },
      crisis: {
        headline: "El FMI advierte que deuda global y energía elevan riesgos fiscales",
        source: "The Guardian",
        date: "15 abr 2026",
        url: "https://www.theguardian.com/business/2026/apr/15/iran-war-global-debt-imf-prices-growth",
        summary: "La eurozona sirve para revisar por qué la crisis de deuda soberana de 2010 sigue siendo referencia.",
      },
      cases: {
        headline: "El euro vuelve a enfrentar el dilema entre inflación, deuda y apoyo fiscal",
        source: "Banco Central Europeo",
        date: "17 abr 2026",
        url: "https://www.ecb.europa.eu/press/stats/bop/2026/html/ecb.bp260417~8cf2910734.hr.html",
        summary: "Es el país/área más útil para explicar problemas del euro desde datos recientes.",
      },
    },
  },
};

const TOPIC_SOURCE = {
  "global-finance": "global",
  origins: "global",
  interdependence: "global",
  "globalization-concept": "global",
  "globalization-risks": "crisis",
  ims: "fx",
  "monetary-systems": "fx",
  "ims-history": "fx",
  "bop-crisis": "crisis",
  bop: "bop",
  "bop-components": "bop",
  transactions: "bop",
  "bop-interpretation": "bop",
  "double-entry": "bop",
  "mexico-current-account": "bop",
  "fx-theory": "fx",
  "fx-market": "fx",
  "cross-rate": "fx",
  "effective-rate": "fx",
  ppp: "fx",
  fisher: "fx",
  "real-rate": "fx",
  "derivatives-market": "derivatives",
  "derivative-instrument": "derivatives",
  "forward-contracts": "derivatives",
  forward: "derivatives",
  futures: "derivatives",
  options: "derivatives",
  "closing-forward": "derivatives",
  "forward-futures-diff": "derivatives",
  "fx-swaps": "derivatives",
  "currency-financial-crises": "crisis",
  "contemporary-currency-crises": "crisis",
  "contemporary-bop-crises": "crisis",
  "international-cases": "cases",
  "china-rise": "cases",
  "power-shift": "cases",
  "crisis-2008": "crisis",
  "sovereign-debt-2010": "crisis",
  "euro-problems": "cases",
};

const TOPIC_CLASSROOM_NOTES = {
  "global-finance": "Úsalo para explicar cómo crecimiento, inversión extranjera, comercio y tasas conectan a México con los mercados financieros internacionales.",
  origins: "Conecta con los orígenes porque muestra la función básica de las finanzas internacionales: financiar comercio, inversión y pagos entre países.",
  interdependence: "Sirve para ver interdependencia: México depende de demanda externa, inversión, cadenas productivas y reglas comerciales de Norteamérica.",
  "globalization-concept": "Ejemplifica globalización porque muestra integración de producción, capital, comercio y decisiones de política económica entre países.",
  "globalization-risks": "Conecta con críticas y riesgos porque muestra vulnerabilidad ante inflación, bajo crecimiento, cambios comerciales y choques externos.",
  ims: "Relaciona el Sistema Monetario Internacional con México al mostrar cómo tasas, dólar y confianza afectan el valor del peso.",
  "monetary-systems": "Sirve para comparar sistemas monetarios porque enseña el papel de bancos centrales, tasas de interés y monedas nacionales frente al dólar.",
  "ims-history": "Ayuda a enlazar la historia del sistema monetario con el presente: hoy el ajuste ocurre vía tipos de cambio, tasas y flujos financieros.",
  "bop-crisis": "Conecta con crisis de balanza de pagos porque permite identificar señales de presión externa antes de que se vuelvan una crisis abierta.",
  bop: "Es una aplicación directa de balanza de pagos: muestra cuenta corriente, exportaciones, importaciones, remesas, IED y relación con el exterior.",
  "bop-components": "Úsalo para separar componentes: cuenta corriente, mercancías, servicios, ingreso primario, ingreso secundario e inversión extranjera.",
  transactions: "Conecta con transacciones registradas porque presenta operaciones reales de comercio, inversión y pagos externos de México.",
  "bop-interpretation": "Sirve para interpretar si un saldo externo refleja fortaleza, debilidad de demanda interna o dependencia de financiamiento externo.",
  "double-entry": "La balanza de pagos usa contabilidad doble: cada entrada de divisas tiene una contraparte financiera, comercial o de ingreso.",
  "mexico-current-account": "Es el caso central de México: cuenta corriente, déficit/superávit, exportaciones, importaciones y financiamiento externo.",
  "fx-theory": "Conecta con teoría cambiaria porque muestra cómo tasas, inflación, expectativas y riesgo mueven el peso frente al dólar.",
  "fx-market": "Sirve para explicar el mercado de divisas: participantes reaccionan a Banxico, dólar global, tasas y noticias de riesgo.",
  "cross-rate": "Permite hablar de tipo de cambio cruzado porque el peso se interpreta frente al dólar y, por esa vía, frente a otras monedas.",
  "effective-rate": "Conecta con tipo de cambio efectivo porque el peso no importa solo contra el dólar, sino frente a socios comerciales relevantes.",
  ppp: "Sirve para paridad del poder adquisitivo porque inflación y precios relativos ayudan a explicar presiones de largo plazo sobre el tipo de cambio.",
  fisher: "Conecta con el Efecto Fisher porque tasas nominales, inflación esperada y rendimiento en pesos influyen en decisiones cambiarias.",
  "real-rate": "Relaciona tipo de cambio real con inflación y competitividad: no basta ver el peso nominal, también importan precios relativos.",
  "derivatives-market": "Es mercado de derivados porque las notas hablan de MexDer, coberturas, volatilidad, futuros, opciones y swaps.",
  "derivative-instrument": "Conecta con instrumento derivado porque estos contratos toman valor de un subyacente: dólar, acciones, tasas o índices.",
  "forward-contracts": "Sirve para contratos a plazo porque la lógica de cobertura es pactar hoy condiciones para reducir incertidumbre futura.",
  forward: "Conecta con forwards al mostrar necesidad de cubrir exposición futura al dólar o a tasas, aunque algunas notas usen mercados organizados.",
  futures: "Es directo para futuros: MexDer lista contratos estandarizados para operar exposición a acciones, divisas o tasas.",
  options: "Es directo para opciones: las noticias de MexDer muestran derechos de compra/venta y cobertura ante volatilidad.",
  "closing-forward": "Permite explicar cierre de posiciones porque la cobertura se ajusta o liquida cuando cambia el riesgo de mercado.",
  "forward-futures-diff": "Sirve para contrastar forwards y futuros: cobertura personalizada contra contratos estandarizados en mercados como MexDer.",
  "fx-swaps": "Conecta con swaps porque muestra instrumentos ligados a TIIE y cobertura de tasas; la misma lógica aplica a swaps de divisas.",
  "currency-financial-crises": "Relaciona crisis cambiarias y financieras con señales de presión: inflación, tasas, depreciación y menor crecimiento.",
  "contemporary-currency-crises": "Sirve para crisis cambiarias contemporáneas porque muestra cómo un recorte de tasas o shock externo puede mover la moneda.",
  "contemporary-bop-crises": "Conecta con crisis modernas de balanza de pagos al observar déficit externo, financiamiento y confianza antes de una ruptura.",
  "international-cases": "Funciona como caso internacional desde México: IED, T-MEC y crecimiento muestran cómo un país se inserta en el sistema global.",
  "china-rise": "Conecta con China por contraste: el nearshoring en México responde al reacomodo de cadenas que antes dependían más de Asia.",
  "power-shift": "Sirve para cambio de poder económico mundial porque México gana peso al reordenarse producción, inversión y comercio global.",
  "crisis-2008": "No trata la crisis de 2008 como noticia actual; usa México para comparar riesgos financieros modernos con lecciones de esa crisis.",
  "sovereign-debt-2010": "Conecta por comparación: deuda, tasas, crecimiento e inflación ayudan a entender por qué las crisis soberanas se vuelven sistémicas.",
  "euro-problems": "No es una noticia del euro; es un contraste con México para explicar cómo una moneda/región enfrenta tensiones de deuda, crecimiento y política monetaria.",
};

function buildTopicNews(countryKey, country) {
  return TOPICS.map((topic) => {
    const sourceKey = TOPIC_SOURCE[topic.id] || "global";
    const stories = [country.sources[sourceKey]].flat();
    const story = stories[0];
    const special =
      topic.id === "mexico-current-account" && countryKey !== "Mexico"
        ? `Comparalo con México: este dato de ${country.displayName} ayuda a ver si una cuenta corriente depende más de comercio, renta de inversiones o flujos financieros.`
        : TOPIC_CLASSROOM_NOTES[topic.id] ||
          `Conecta con "${topic.label}" porque muestra el tema aplicado a ${country.displayName} con datos recientes.`;

    return {
      ...topic,
      country: countryKey,
      title: story.headline,
      source: stories.length > 1 ? `${stories.length} noticias` : story.source,
      date: story.date,
      url: story.url,
      summary: story.summary,
      classroomNote: special,
      stories: stories.map((item) => ({
        ...item,
        classroomNote: special,
      })),
    };
  });
}

export const COUNTRY_BRIEFINGS = Object.fromEntries(
  Object.entries(COUNTRY_LIBRARY).map(([key, country]) => [
    key,
    {
      ...country,
      topics: buildTopicNews(key, country),
    },
  ]),
);

export const AVAILABLE_COUNTRIES = Object.keys(COUNTRY_BRIEFINGS);
